services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
  catalog:
    build:
      context: catalog
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./catalog/.env
    ports:
      - 3000:3000
    volumes:
      - ./catalog:/usr/src/app
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./auth/.env
    ports:
      - 3001:3001
    volumes:
      - ./auth:/usr/src/app
  activity:
    build:
      context: activity
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./activity/.env
    ports:
      - 3003:3003
      - 4000:4000
    volumes:
      - ./activity:/usr/src/app
  statistics:
    build:
      context: statistics
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./statistics/.env
    ports:
      - 3005:3005
      - 4001:4001
    volumes:
      - ./statistics:/usr/src/app
